### ISSUE TITLE
Google Admob 

### ISSUE THREAD

**Issue by dev-jw** [JonyFang/FFPopup#11]
When I use Google Admob, the pop can't show

**Comment by JonyFang** [comment]
Hi @SmallLion ,

Your problem description is a bit fuzzy. You can provide a demo project(demo repo link) and the steps to reproduce the issue, which will help us find the cause of the problem. 

In addition, filling in the detailed description of the issue is also helpful.

**Comment by cevanish12** [comment]
I noticed this issue as well. I believe admob adds a UIWindow to your app and my guess is that the popup is added to the wrong UIWindow. I managed to fix it by checking that the window is also the keyWindow when iterating through all the windows in the showWithParameters method.

**Comment by SmallLion** [comment]
@cevanish12 so, you solve it?

**Comment by MinOhPark** [comment]
I encountered the same issue.

**Comment by MinOhPark** [comment]
@cevanish12 's way is helpful to me.

FFPopup.m 

Change the code. When Google AdMob is in my project, there are 2 different window here. the first thing is our original window, the second one is AdMob's. So, add FFPopupView to first window. 
Here is my change

if (!strongSelf.superview) {
                UIWindow *window = [[[UIApplication sharedApplication] windows] firstObject];
                if (window.windowLevel == UIWindowLevelNormal) {
                    [window addSubview:self];
                }
            }
...

**Comment by fengong** [comment]
![image](https://user-images.githubusercontent.com/7297272/75026626-45dcf880-54d8-11ea-969b-9f99693fce46.png)
Hi @JonyFang , here is my solution
```objc
                    if (window.windowLevel == UIWindowLevelNormal && window.isHidden == NO) {
                        [window addSubview:self];
                        break;
                    }
```
