### ISSUE TITLE
install-bundle.sh: line 3: bundle: command not found

### ISSUE THREAD

**Issue by QiuXiaochun** [JonyFang/FFPopup#21]
git clone https://github.com/JonyFang/FFPopup.git

cd Shell && sh install-bundle.sh && sh install-pods.sh && cd ..

the result:
install-bundle.sh: line 3: bundle: command not found

**Comment by JonyFang** [comment]
It seems that [Bundler](http://bundler.io/) is not installed in your mac.

You have to `install bundler` first for that.

```bash
$ gem install bundler
```

I hope this will help.

**Comment by QiuXiaochun** [comment]
Yes, I have got it successfully.

Thank you!
