### ISSUE TITLE
 it's not show 

### ISSUE THREAD

**Issue by dslcoding** [JonyFang/FFPopup#22]
- (void)menuAction{
    
    FFPopup *popup = [FFPopup popupWithContentView:self.contentView];
    popup.showType = FFPopupShowType_None;
    popup.dismissType = FFPopupDismissType_None;
    popup.maskType = FFPopupMaskType_None;
    popup.shouldDismissOnBackgroundTouch = YES;
    popup.shouldDismissOnContentTouch = YES;
    FFPopupLayout layout = FFPopupLayoutMake(FFPopupHorizontalLayout_Center, FFPopupVerticalLayout_Center);
    popup.backgroundColor = [UIColor blueColor];
    [popup showWithLayout:layout ];
}

- (BLCustomContentView *)contentView {
    if (!_contentView) {
        CGFloat scale = 375.0 / SCREEN_WIDTH;
        CGFloat width = 320.0 * scale;
        CGFloat height = 360.0 * scale;
        _contentView = [[BLCustomContentView alloc] initWithFrame:CGRectMake(0, 0, width, height)];
        _contentView.backgroundColor = [UIColor redColor];
        [_contentView updateTitle:@"👋\nHurray!" desc:@"Your request has been sent successfully. We will email you shortly. Meantime, check our marketing tips on Twitter and Facebook." buttonTitle:@"Got it"];
        _contentView.delegate = self;
    }
    return _contentView;
}

it is not show ,i don't know ,

**Comment by JonyFang** [comment]
Is there any call stack frame?
